
### Exercises Of Chapter 2, 3 Converted in Python
<b>Ref:</b> <i style="color: gray;"> Gilat, Amos Numerical Methodsfor Engineers and Scientists An introduction</i>


# 6.

Define the variables \( a = 3.5 \), \( b = -6.4 \), and then use them to create a row vector that has the following elements:  a ,  a^2 ,  a/b ,  a.b , and sqrt(a).

In [11]:
from math import sqrt
a = 3.5 # define a
b = -6.4 # define b
vector = [a, a**2, a/b, a*b, sqrt(a)] # building a vector

print("Vector: ", vector)

# In python it's better to use numpy for vectors: 

# import numpy as np
# a = 3.5
# b = -6.4
# row_vector = np.array([a, a**2, a/b, a*b, np.sqrt(a)])


Vector:  [3.5, 12.25, -0.546875, -22.400000000000002, 1.8708286933869707]


# 11.

Using the colon symbol, create a row vector (assign it to a variable named Fives) with five elements that are all 5.

In [12]:
Five = [5 for _ in range(6)]
print("a row vector: ", Five)

# In python it's better to use numpy for vectors: 

# import numpy as np
# Fives = np.ones(5) * 5
# print("a row vector: ", Five)


a row vector:  [5, 5, 5, 5, 5, 5]


# 16.

Create two row vectors:  
a = 2 : 3 : 17  
b = 3 : 4 : 15   

Then, by only using the name of the vectors (a and b), create a row vector \( c \) that is made from the elements of \( a \) followed by the elements of \( b \).

In [ ]:
import numpy as np

a = np.arange(2, 17, 3)
b = np.arange(3, 16, 4)
print("a and b:\n", a,"\n" ,b)
print()
c = np.concatenate((a, b)) # Create c
print("c is equal to:\n", c)


a and b:
 [ 2  5  8 11 14] 
 [ 3  7 11 15]

c is equal to:
 [ 2  5  8 11 14  3  7 11 15]


# 21.

Create the following matrix by using vector notation for creating vectors with constant spacing and/or the `linspace` command. Do not type individual elements explicitly.

$$ A = 
\begin{bmatrix}
130 & 110 & 90 & 70 & 50 & 30 & 10 \\
1 & 2.8333 & 4.6667 & 6.5 & 8.3333 & 10.1667 & 12 \\
12 & 22 & 32 & 42 & 52 & 62 & 72
\end{bmatrix} $$

In [41]:
import numpy as np

row1 = np.arange(130, 9, -20)
row2 = np.linspace(1, 12, 7)
row3 = np.arange(12, 73, 10)

arr = np.vstack([row1, row2, row3])

print("Array:\n", arr)
print("Shape: ", arr.shape)

Array:
 [[130.         110.          90.          70.          50.
   30.          10.        ]
 [  1.           2.83333333   4.66666667   6.5          8.33333333
   10.16666667  12.        ]
 [ 12.          22.          32.          42.          52.
   62.          72.        ]]
Shape:  (3, 7)


# 26.

Create the following matrix by typing one command. Do not type individual elements explicitly.

$$ F = 
\begin{bmatrix}
0 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 10 & 20 \\
0 & 0 & 2 & 8 & 26 \\
0 & 0 & 3 & 6 & 32
\end{bmatrix} $$

In [42]:
import numpy as np

F = np.array([[0,0,0,0,0],
              [0,0,1,10,20],
              [0,0,2,8,26],
              [0,0,3,6,32]])

# 36.

Create the following matrix \( E \):

$$ E = 
\begin{bmatrix}
0 & 5 & 5 & 5 & 5 & 5 \\
0.1 & 0.3 & 0.5 & 0.7 & 0.7 & 0.9 \\
12 & 9 & 6 & 3 & 0 & -3 \\
6 & 7 & 8 & 9 & 10 & 11
\end{bmatrix} $$

(a) Create a \( 2 \times 3 \) matrix \( F \) from the second and third rows, and the third through the fifth columns of matrix \( E \).

(b) Create a \( 4 \times 4 \) matrix \( G \) from all rows and the third through sixth columns of matrix \( E \).

In [69]:
import numpy as np

E = np.array([[0, 5, 5, 5, 5, 5],
             [0.1, 0.3, 0.5, 0.7, 0.7, 0.9],
             [12, 9, 6, 3, 0, -3],
             [6, 7, 8, 9, 10, 11]]
             )
E2 = np.vstack([E[1][2:5], E[2][2:5]]) # or E[1:3, 2:5]
E3 = E[:, 2:6]

print(E2)
print()
print(E3)

[[0.5 0.7 0.7]
 [6.  3.  0. ]]

[[ 5.   5.   5.   5. ]
 [ 0.5  0.7  0.7  0.9]
 [ 6.   3.   0.  -3. ]
 [ 8.   9.  10.  11. ]]


# 41.

Using the `zeros`, `ones`, and `eye` commands, create the following arrays by typing one command:

(a)  
\[
\begin{bmatrix}
1 & 1 & 0 & 0 \\
1 & 1 & 0 & 0
\end{bmatrix}
\]

(b)  
\[
\begin{bmatrix}
1 & 0 & 0 & 0 & 1 \\
0 & 1 & 0 & 0 & 1
\end{bmatrix}
\]

(c)  
\[
\begin{bmatrix}
1 & 1 & 1 & 1 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0
\end{bmatrix}
\]

In [94]:
import numpy as np

M1 = np.hstack([np.ones((2, 2)), np.zeros((2, 2))])
M2 = np.hstack([np.eye(2), np.zeros((2, 2)), np.ones((2,1))])
M3 = np.vstack([np.ones((1, 4)), np.zeros((1, 4)), np.zeros((1, 4))])

print("(a):\n", M1)
print()
print("(b):\n", M2)
print()
print("(c):\n", M3)

(a):
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]]

(b):
 [[1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]]

(c):
 [[1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Chapter 3 

# 1.

For the function \( y = x^2 - e^{0.5x} + x \), calculate the value of \( y \) for the following values of \( x \) using element-by-element operations: \( -3, -2, -1, 0, 1, 2, 3 \).

In [5]:
from math import exp
def equ(lis):
    for x in lis:
        yield x ** 2 - exp(0.5 * x) + x

lis = [-3, -2, -1, 0, 1, 2, 3]

from math import exp

# Iterate over
for y in equ(lis):
    print(y)

5.776869839851571
1.6321205588285577
-0.6065306597126334
-1.0
0.3512787292998718
3.281718171540955
7.5183109296619355


# 6. Electric Field Intensity Along the Axis of a Charged Ring

The electric field intensity, \( E(z) \), due to a ring of radius \( R \) at any point \( z \) along the axis of the ring is given by:

$$
E(z) = \frac{\lambda}{2\epsilon_0} \cdot \frac{1}{(z^2 + R^2)^{3/2}}
$$

where  
- lambda is the charge density (C/m),  
-  epsilon_0 = 8.85 times 10^{-12} , C^{N·m}^2  is the electric constant,  
-  R  is the radius of the ring (m).

Consider the case where  
$$
\lambda = 1.7 \times 10^{-7} \, \text{C/m}, \qquad R = 6 \, \text{cm} = 0.06 \, \text{m}.
$$

### (a)
Determine  E(z)  at  z = 0, 2, 4, 6, 8, 10 , cm  (convert to meters when evaluating).

### (b)
Determine the distance  z  where E  is maximum.  
Do this by creating a vector  z  with elements ranging from  2cm  to  6cm  and spacing of  0.01cm.  
Calculate  E  for each value of  z  and then find the maximum  E  and associated  z  using MATLAB’s built‑in function `max`.

In [19]:
import numpy as np

l = 1.7 * 10**(-7)        
R = 6 * 10**(-2)            
e = 8.85 * 10**(-12)        

def Electrical_field(lis):
    for z in lis:
        yield (l / (2 * e)) * (1 / ((z**2 + R**2) ** (3/2)))

# Part (a)
z_cm = [0, 2, 4, 6, 8, 10]
z_m = [x * 0.01 for x in z_cm]      
for y in Electrical_field(z_m):
    print(y)

# Part (b)
z_cm_b = np.arange(2.0, 6.01, 0.01)  
z_m_b = z_cm_b * 0.01                

maximum = -1e9
max_idx = 0
for idx, y in enumerate(Electrical_field(z_m_b)):
    if y > maximum:
        maximum = y
        max_idx = idx

print()
print(f"The maximum field is at {z_cm_b[idx]}m, equals to {maximum}")


44465369.324126385
37965197.89750173
25613600.977370966
15720882.088527031
9604519.774011299
6055741.000794803

The maximum field is at 5.999999999999915m, equals to 37965197.89750173


# 11.

Two vectors are given:

$$ \mathbf{u} = 5\mathbf{i} - 6\mathbf{j} + 9\mathbf{k} $$

$$ \mathbf{v} = 11\mathbf{i} + 7\mathbf{j} - 4\mathbf{k} $$

Use MATLAB to calculate the dot product \( \mathbf{u} \cdot \mathbf{v} \) of the vectors in three ways:

(a) Write an expression using element-by-element calculation and the MATLAB built-in function `sum`.

(b) Define \( \mathbf{u} \) as a row vector and \( \mathbf{v} \) as a column vector, and then use matrix multiplication.

(c) Use the MATLAB built-in function `dot`.

In [20]:
import numpy as np


u = np.array([5, -6, +9])
v = np.array([11, 7, -4])

a = np.sum(u * v)

u_row = u.reshape(1, -1)   # 1*3
v_col = v.reshape(-1, 1)   # 3*1

b = (u_row @ v_col).item() 


c = np.dot(u, v) 

print(a)
print(b)
print(c)

-23
-23
-23


# 16.

The area of a triangle $ABC$ can be calculated by

$$
\text{Area} = \frac{|\vec{r}_{AB} \times \vec{r}_{AC}|}{2}
$$

where $\vec{r}_{AB}$ and $\vec{r}_{AC}$ are vectors connecting the vertices $A$ and $B$, and $A$ and $C$, respectively. Determine the area of the triangle shown in the figure. Use the following steps in a script file to calculate the area. First, define the vectors $\vec{r}_{OA}$, $\vec{r}_{OB}$ and $\vec{r}_{OC}$ from knowing the coordinates of points $A$, $B$, and $C$. Then determine the vectors $\vec{r}_{AB}$ and $\vec{r}_{AC}$ from $\vec{r}_{OA}$, $\vec{r}_{OB}$ and $\vec{r}_{OC}$. Finally, determine the area by using MATLAB's built-in functions `cross`, `sum`, and `sqrt`.

In [24]:
import numpy as np

# points
A = [8, 5, -4]
B = [-7, 9, 6]
C = [-5, -2, 11]

# points to vectors
ra = np.array(A)
rb = np.array(B)
rc = np.array(C)

# rab, rac
rab = ra - rb
rac = ra - rc

# area
cross_prod = np.cross(rab, rac)
abs = np.sqrt(np.sum(cross_prod ** 2))
area = abs / 2

print("Area of the triangle ABC is equal to: ", area)

Area of the triangle ABC is equal to:  112.44331905453521


# 21.

The position as a function of time \( (x(t), y(t)) \) of a projectile fired with a speed of \( v_0 \) at an angle \( \alpha \) is given by

$$
x(t) = v_0 \cos \alpha \cdot t \qquad y(t) = v_0 \sin \alpha \cdot t - \frac{1}{2} g t^2
$$

where \( g = 9.81 \, \text{m/s}^2 \). The polar coordinates of the projectile at time \( t \) are \( (r(t), \theta(t)) \), where

$$
r(t) = \sqrt{x(t)^2 + y(t)^2} \qquad \text{and} \qquad \tan \theta(t) = \frac{y(t)}{x(t)}.
$$

Consider the case where

$$
v_0 = 162 \, \text{m/s} \quad \text{and} \quad \alpha = 70^\circ.
$$

Determine r(t) and theta for \( t = 1, 6, 11, ...., 31 (s). \)

In [37]:
from math import cos, sin, pi
import numpy as np

a = 70 * pi/180
v0 = 162
g = 9.81

def calculation(t):
    X_t = v0 * cos(a) * t
    Y_t = v0 * sin(a) * t - 0.5 * g * t**2
    tant = np.arctan2(Y_t, X_t)
    r_t = np.sqrt(X_t**2 + Y_t**2)
    return tant, r_t

t_ = np.arange(1, 32, 5)
for t in t_:
    theta, r = calculation(t)  
    print(f"t={t:2d}s, theta={np.degrees(theta):.2f}°, r={r:.2f}m")

t= 1s, theta=69.39°, r=157.40m
t= 6s, theta=65.72°, r=808.33m
t=11s, theta=60.59°, r=1241.00m
t=16s, theta=53.08°, r=1475.91m
t=21s, theta=41.62°, r=1556.42m
t=26s, theta=24.03°, r=1577.25m
t=31s, theta=0.18°, r=1717.63m


# 26.

Show that

$$
\frac{x^{1/3} - 1}{x^{1/4} - 1} = \frac{4}{3}.
$$

Do this by first creating a vector $x$ that has the elements 2.0, 1.5, 1.1, 1.01, 1.001, 1.00001, and 1.0000001. Then, create a new vector $y$ in which each element is determined from the elements of $x$ by

$$
\frac{x^{1/3} - 1}{x^{1/4} - 1}.
$$

Compare the elements of $y$ with the value $4/3$ (use `format long` to display the numbers).

In [45]:
import numpy as np

x = [2.0, 1.5, 1.1, 1.01, 1.001, 1.0001, 1.00001, 1.000001, 10000001]
y = [(x**1/3 -1)/(x**1/4-1) for x in x]
# print(y)
print('4/3 is equal to = ',4/3)

print('and the limit awnser is: ',y[-1])

4/3 is equal to =  1.3333333333333333
and the limit awnser is:  1.3333334666667067


# 31.

Create a  4 * 4  matrix  A  having random integer values between 1 and 10. Call the matrix  A  and, using MATLAB, perform the following operations. For each part explain the operation.

(a) A * A   

(b) A .* A  

(c) A \ A 

(d) A ./ A 

(e) det(A) 

(f) inv(A)

In [46]:
import numpy as np

A = np.random.randint(1, 11, size=(4, 4))

print(A)
print("\nA * A =")
print(A @ A)
print("\nA .* A =")
print(A * A)

print("\nA \\ A =")
try:
    print(np.linalg.solve(A, A))
except:
    print("matrix is singular")

print(A / A)

print("\ndet(A)")
print(np.linalg.det(A))

print("\ninv(A)")
print(np.linalg.inv(A))

[[ 7  6 10  2]
 [ 3  5  9  8]
 [ 5  5  7  6]
 [ 3  3  2 10]]

A * A =
[[123 128 198 142]
 [105 112 154 180]
 [103 108 156 152]
 [ 70  73  91 142]]

A .* A =
[[ 49  36 100   4]
 [  9  25  81  64]
 [ 25  25  49  36]
 [  9   9   4 100]]

A \ A =
[[ 1.00000000e+00  0.00000000e+00 -4.32893684e-16  1.39514565e-15]
 [ 4.99300301e-15  1.00000000e+00  1.09716158e-15 -3.67494911e-15]
 [-1.60832308e-15 -0.00000000e+00  1.00000000e+00  1.13954967e-15]
 [-6.36127787e-16 -0.00000000e+00 -1.59031947e-16  1.00000000e+00]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

det(A)
-74.0000000000003

inv(A)
[[ 1.16216216  0.08108108 -2.02702703  0.91891892]
 [-2.72972973 -0.86486486  5.62162162 -2.13513514]
 [ 0.86486486  0.43243243 -1.81081081  0.56756757]
 [ 0.2972973   0.14864865 -0.71621622  0.35135135]]
