# Amin Mottaghi -- S2
### Exercises Of Chapter 2, 3 Converted in Python
<b>Ref:</b> <i style="color: gray;"> Gilat, Amos Numerical Methodsfor Engineers and Scientists An introduction</i>


# 6.

Define the variables \( a = 3.5 \), \( b = -6.4 \), and then use them to create a row vector that has the following elements:  a ,  a^2 ,  a/b ,  a.b , and sqrt(a).

In [11]:
from math import sqrt
a = 3.5 # define a
b = -6.4 # define b
vector = [a, a**2, a/b, a*b, sqrt(a)] # building a vector

print("Vector: ", vector)

# In python it's better to use numpy for vectors: 

# import numpy as np
# a = 3.5
# b = -6.4
# row_vector = np.array([a, a**2, a/b, a*b, np.sqrt(a)])


Vector:  [3.5, 12.25, -0.546875, -22.400000000000002, 1.8708286933869707]


# 11.

Using the colon symbol, create a row vector (assign it to a variable named Fives) with five elements that are all 5.

In [12]:
Five = [5 for _ in range(6)]
print("a row vector: ", Five)

# In python it's better to use numpy for vectors: 

# import numpy as np
# Fives = np.ones(5) * 5
# print("a row vector: ", Five)


a row vector:  [5, 5, 5, 5, 5, 5]


# 16.

Create two row vectors:  
a = 2 : 3 : 17  
b = 3 : 4 : 15   

Then, by only using the name of the vectors (a and b), create a row vector \( c \) that is made from the elements of \( a \) followed by the elements of \( b \).

In [ ]:
import numpy as np

a = np.arange(2, 17, 3)
b = np.arange(3, 16, 4)
print("a and b:\n", a,"\n" ,b)
print()
c = np.concatenate((a, b)) # Create c
print("c is equal to:\n", c)


a and b:
 [ 2  5  8 11 14] 
 [ 3  7 11 15]

c is equal to:
 [ 2  5  8 11 14  3  7 11 15]


# 21.

Create the following matrix by using vector notation for creating vectors with constant spacing and/or the `linspace` command. Do not type individual elements explicitly.

$$ A = 
\begin{bmatrix}
130 & 110 & 90 & 70 & 50 & 30 & 10 \\
1 & 2.8333 & 4.6667 & 6.5 & 8.3333 & 10.1667 & 12 \\
12 & 22 & 32 & 42 & 52 & 62 & 72
\end{bmatrix} $$

In [41]:
import numpy as np

row1 = np.arange(130, 9, -20)
row2 = np.linspace(1, 12, 7)
row3 = np.arange(12, 73, 10)

arr = np.vstack([row1, row2, row3])

print("Array:\n", arr)
print("Shape: ", arr.shape)

Array:
 [[130.         110.          90.          70.          50.
   30.          10.        ]
 [  1.           2.83333333   4.66666667   6.5          8.33333333
   10.16666667  12.        ]
 [ 12.          22.          32.          42.          52.
   62.          72.        ]]
Shape:  (3, 7)


# 26.

Create the following matrix by typing one command. Do not type individual elements explicitly.

$$ F = 
\begin{bmatrix}
0 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 10 & 20 \\
0 & 0 & 2 & 8 & 26 \\
0 & 0 & 3 & 6 & 32
\end{bmatrix} $$

In [42]:
import numpy as np

F = np.array([[0,0,0,0,0],
              [0,0,1,10,20],
              [0,0,2,8,26],
              [0,0,3,6,32]])

# 36.

Create the following matrix \( E \):

$$ E = 
\begin{bmatrix}
0 & 5 & 5 & 5 & 5 & 5 \\
0.1 & 0.3 & 0.5 & 0.7 & 0.7 & 0.9 \\
12 & 9 & 6 & 3 & 0 & -3 \\
6 & 7 & 8 & 9 & 10 & 11
\end{bmatrix} $$

(a) Create a \( 2 \times 3 \) matrix \( F \) from the second and third rows, and the third through the fifth columns of matrix \( E \).

(b) Create a \( 4 \times 4 \) matrix \( G \) from all rows and the third through sixth columns of matrix \( E \).

In [69]:
import numpy as np

E = np.array([[0, 5, 5, 5, 5, 5],
             [0.1, 0.3, 0.5, 0.7, 0.7, 0.9],
             [12, 9, 6, 3, 0, -3],
             [6, 7, 8, 9, 10, 11]]
             )
E2 = np.vstack([E[1][2:5], E[2][2:5]]) # or E[1:3, 2:5]
E3 = E[:, 2:6]

print(E2)
print()
print(E3)

[[0.5 0.7 0.7]
 [6.  3.  0. ]]

[[ 5.   5.   5.   5. ]
 [ 0.5  0.7  0.7  0.9]
 [ 6.   3.   0.  -3. ]
 [ 8.   9.  10.  11. ]]


# 41.

Using the `zeros`, `ones`, and `eye` commands, create the following arrays by typing one command:

(a)  
\[
\begin{bmatrix}
1 & 1 & 0 & 0 \\
1 & 1 & 0 & 0
\end{bmatrix}
\]

(b)  
\[
\begin{bmatrix}
1 & 0 & 0 & 0 & 1 \\
0 & 1 & 0 & 0 & 1
\end{bmatrix}
\]

(c)  
\[
\begin{bmatrix}
1 & 1 & 1 & 1 \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0
\end{bmatrix}
\]

In [94]:
import numpy as np

M1 = np.hstack([np.ones((2, 2)), np.zeros((2, 2))])
M2 = np.hstack([np.eye(2), np.zeros((2, 2)), np.ones((2,1))])
M3 = np.vstack([np.ones((1, 4)), np.zeros((1, 4)), np.zeros((1, 4))])

print("(a):\n", M1)
print()
print("(b):\n", M2)
print()
print("(c):\n", M3)

(a):
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]]

(b):
 [[1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]]

(c):
 [[1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
